### ISSUE TITLE
Create placeholders for boxes that do not have cover image

### ISSUE THREAD

**Issue by mspanc** [audioasyl/website#1]

**Comment by Manovski** [comment]
![venue](https://cloud.githubusercontent.com/assets/17588878/23668430/57c655ee-0361-11e7-8233-aff553d6e4b4.png)
![archive](https://cloud.githubusercontent.com/assets/17588878/23668432/57c6baf2-0361-11e7-8261-9f0f809f67c5.png)
![host](https://cloud.githubusercontent.com/assets/17588878/23668433/57c8a6be-0361-11e7-834b-c97cfa6a7b12.png)
![show](https://cloud.githubusercontent.com/assets/17588878/23668431/57c6b750-0361-11e7-88cf-a17836f2c1d3.png)

**Comment by mspanc** [comment]
@Manovski I think we have misunderstanding here.

I meant rather generating them randomly in the code. Like colorful mosaic with tiles etc.
