### ISSUE TITLE
Remove duplicate channel names in channel view

### ISSUE THREAD

**Issue by Manovski** [audioasyl/website#18]
Currently we have channel name twice in each channel view, there should be only one in the description box so we need to remove the other that is written above the player in the channel view.

**Comment by konrad-marzec** [comment]
I think it should be done in backend.

**Comment by Manovski** [comment]
@konrad-marzec  Are you sure? This is what they meant. 

![untitled](https://cloud.githubusercontent.com/assets/17588878/24950567/bfa9bdfa-1f71-11e7-9759-0d4ec24d84dd.png)
