### ISSUE TITLE
Top bar is over part of the first section

### ISSUE THREAD

**Issue by mspanc** [audioasyl/website#3]
On firefox/mac, upon loading the page, top bar is over part of the first section so "SHOWS" section title is invisible.

![screen shot 2017-03-29 at 18 41 33](https://cloud.githubusercontent.com/assets/389651/24465988/7ef50390-14af-11e7-800c-ebd3ec4f0f30.png)

CC @Manovski 
Related to https://github.com/radiokit/deployments/issues/12

**Comment by konrad-marzec** [comment]
We retain scroll. So it was probably your previous scroll position.
